# netlify.toml

[build]
  publish = "build"  # The folder where your React build files are located
  command = "npm run build"  # Build command for React app (or yarn build)

[[redirects]]
  # Catch-all redirect for client-side routing (React Router)
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  # Specific redirect for /admin-login route (Optional)
  from = "/admin-login"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  # Specific redirect for /admin-panel route (Optional)
  from = "/admin-panel"
  to = "/index.html"
  status = 200
  force = true
